### ISSUE TITLE
No screenshots, test session freeze on more than 1 device

### ISSUE THREAD

**Issue by FisherHUB** [stanfy/spoon-gradle-plugin#100]
Hello,

After updating spoon-runner to 1.3.1 and spoon-plugin to 1.0.5-SNAPSHOT I cannot fetch any screenshots from devices - either on 6.0 or lower Android versions.

> [device name] Unable to find test for [test name] 

-> and that info for every test I have. I am using gradle 1.5.0.

----

Furthermore if I use two devices or more then after tests finish at line:

> 
[SDR.run] Moving screenshots to the image folder on [device name] 

I get freeze. This line will load forever, I waited 30-40mins. Always on the device which ends as last one. Doesn't happen if I run tests only at one device.

**Comment by roman-mazur** [comment]
I've just tried to run tests with spoon on Android 5.1 device using example project here. And it works (not counting problems with getting logcat output), screenshots are fetched. Could you please check if the example project works for you.

Also this plugin has no changes in 1.0.5-SNAPSHOT. Hence, I would suggest using 1.0.4 release version to avoid any future problems with snapshots.

**Comment by originx** [comment]
I have the same issue with stated versions, the test run hangs forever saying execution finished waiting for devices [xxxxxxxxx]
Could it be that something crashes instrumentation and spoon is endlessly waiting it to finish?

(this mostly occurs on Samsung devices)

**Comment by FisherHUB** [comment]
Thanks Roman.

Problem was on my side. I set some flags that turn on/off screenshots and during some refactors it affected my tests. After I repaired it everything works fine, even on gradle 2.0.0-alpha9.
