### ISSUE TITLE
Question/Request: Can you create a release so as to use shard option

### ISSUE THREAD

**Issue by hewhomustnotbenamed** [stanfy/spoon-gradle-plugin#109]
Hi @roman-mazur, I need to use shard option in my project. Can you release or create a developer commit so that I can you your repo as is. 

Thanks

**Comment by roman-mazur** [comment]
Sorry, did not notice this issue. 

The latest version (1.1.1-SNAPSHOT) is available in the snapshots repository:
```
maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
```

I plan to release 1.1.1 by Monday, maybe faster, depending on the feedback we'll get regarding
https://code.google.com/p/android/issues/detail?id=210444
