### ISSUE TITLE
No such property: shard

### ISSUE THREAD

**Issue by maclir** [stanfy/spoon-gradle-plugin#110]
When I put `shard = true` in my spoon options I get the following error:

```
No such property: shard for class: com.stanfy.spoon.gradle.SpoonExtension_Decorated
```

**Comment by roman-mazur** [comment]
That's because the readme documents what's in the master branch. And the latest version which supports "shard" configuration is not released yet.

**Comment by maclir** [comment]
Is there a timeframe on when the next release will be?

**Comment by roman-mazur** [comment]
hopefully next week

**Comment by roman-mazur** [comment]
The latest version (1.1.1-SNAPSHOT) is available in the snapshots repository:

maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
I plan to release 1.1.1 by Monday, maybe faster, depending on the feedback we'll get regarding
https://code.google.com/p/android/issues/detail?id=210444

**Comment by roman-mazur** [comment]
Version 1.2.0 is released and will be available in Maven Central in few hours.
