### ISSUE TITLE
projectOutput.assemble is returning null using latest 2.2-alpha2 plugin

### ISSUE THREAD

**Issue by cooperkong** [stanfy/spoon-gradle-plugin#112]
looks like this is the root cause of #107 , assemble has the actual task when tested with pre 2.2, but is returning null in 2.2-alpha2
`        dependsOn projectOutput.assemble, testVariant.assemble
`

**Comment by roman-mazur** [comment]
I can confirm this. Created a branch with a dependency on 2.2.0-alpha1 to reproduce the issue and updated https://code.google.com/p/android/issues/detail?id=210444

But let's keep everything on one place. I will close this issue, we can continue discussion in #107.
