### ISSUE TITLE
Getting 'Error:Access to the dex task is now impossible' after adding spoon gradle plugin

### ISSUE THREAD

**Issue by amith007** [stanfy/spoon-gradle-plugin#114]
I am always getting the below error when I sync after adding the Spoon gradle plugin.

Error:Access to the dex task is now impossible, starting with 1.4.0
1.4.0 introduces a new Transform API allowing manipulation of the .class files.
See more information: http://tools.android.com/tech-docs/new-build-system/transform-api

I have set my project to use gradle version 1.2.3 to avoid similar issues i had earlier. However that is not solving the issue that I am facing with spoon plugin.

Is there any min gradle version for this plugin? or am I doing something wrong?

**Comment by roman-mazur** [comment]
And example project in this repo uses Gradle plugin 2.0.0
I'm not sure that latest spoon plugin versions are compatible with Android plugin below 1.5.0.

If you need to use Android plugin of version <1.5, you might trying checking out an older version of this plugin (maybe 1.0.3). But I would rather switch to newer Android plugin version.

If you still have a problem, please try to reproduce it on the example project in this repo and feel free to reopen the ticket.

**Comment by amith007** [comment]
1.0.3 seems to work. The issue with upgrading the project is that I am not the owner :). I am an automation engineer for the team and project is huge. However I might take a stab at it on my branch :). Thanks @roman-mazur
