### ISSUE TITLE
Error while merging coverage files

### ISSUE THREAD

**Issue by pawelkw** [stanfy/spoon-gradle-plugin#115]
Hey.

I have the following error after all my tests finish executing and spoon is generating the report:
`error while merging coverage files`
`Caused by: java.io.FileNotFoundException .../coverage/[somehash]/coverage.ec (No such file or directory)`
I'm running a single test class, on a single physical device. I didn't try running everything or a single test method.
I've ran clean first, didn't help.
Version 1.2.0.

**Comment by roman-mazur** [comment]
Hi @pawelkw 
Does it happen even if you disable test coverage?

**Comment by pawelkw** [comment]
Nope. Works correctly without the `codeCoverage = true` flag.

**Comment by roman-mazur** [comment]
It looks like there some problems obtaining the coverage file from your device. It's not pulled and coverage merger then fails to open it.
@pawelkw Would you describe your device environment (real device or emulator, Android version)?

/cc @jainsahab

**Comment by pawelkw** [comment]
Real Device. Samsung Galaxy S6 (SM-G920F). Android 6.0.1. Samsung build number: MMB29K.G920FXXU3DPDP.

**Comment by pawelkw** [comment]
Same problem on Nexus 5 (not 5X).

**Comment by pawelkw** [comment]
Also on Huawei P8 Lite.

**Comment by pawelkw** [comment]
My config:

```
spoon {
    debug = true
    // Enable setting test class/method-to-be-run from command line. E.g.:
    // $> ../gradlew spoonFreeDebugTest -PspoonClassName=com.stanfy.spoon.example.test.MainActivityTest -PspoonMethodName=testSetText
    if (project.hasProperty('spoonClassName')) {
        className = project.spoonClassName

        if (project.hasProperty('spoonMethodName')) {
            methodName = project.spoonMethodName
        }
    }

    adbTimeout = 60 * 3
    codeCoverage = true
}
```

I'm running:
`./gradlew clean spoon[MyVariant] -PspoonClassName=my.test.Class`

**Comment by pawelkw** [comment]
Also on emulator.

**Comment by hewhomustnotbenamed** [comment]
This is the issue with Spoon itself on which this plugin depends on. I have raised the request with that repo [#346](https://github.com/square/spoon/issues/346). Hopefully fixing that should also fix this issue

**Comment by jainsahab** [comment]
I've commented on that [https://github.com/square/spoon/issues/346](issue). I will pick that up soon.

**Comment by pawelkw** [comment]
Awesome. I've seen that threre's a PR already. I'll re-test and let you know if it fixed the issue for me once  it's merged.

**Comment by jainsahab** [comment]
I've put a [fix](https://github.com/stanfy/spoon-gradle-plugin/pull/117) for this issue.
