### ISSUE TITLE
Exclude specific devices

### ISSUE THREAD

**Issue by originx** [stanfy/spoon-gradle-plugin#118]
Hello,

is there a possibility to exclude specific devices for test runs instead of defining all the devices on which the tests should run?

Thanks!

**Comment by roman-mazur** [comment]
No, there is no such functionality. PRs are welcome!

**Comment by originx** [comment]
Thanks for the info, if I find time PR will be sent.

Cheers

**Comment by originx** [comment]
#126 opened PR for this

**Comment by originx** [comment]
merged  #126
