### ISSUE TITLE
How to set property or listen to spoon task that some test failed?

### ISSUE THREAD

**Issue by Pavel87** [stanfy/spoon-gradle-plugin#127]
I am running 4 spoon tasks for 4 different modules with "ignoreFailure=true" flag  as part of parent task however I need to somehow capture that there was a failure so I can fail the parent task at the very end. Is that currently possible to do so?

These two links may help out asses if it can be done with spoon. There seems to be a way of using test listeners when running standard tests.
https://discuss.gradle.org/t/can-you-set-a-property-to-defer-test-failure/4501/3
https://issues.gradle.org/browse/GRADLE-1554

**Comment by roman-mazur** [comment]
It's not possible with the current plugin. It's questionable if it's worth implementing though.
Note that gradle has a `--continue` command line flag that allows you continue tasks execution even if some test task fails. You might try removing `ignoreFailure` and adding `--continue`. This should execute tasks that depend on spoon task but build will still fail in case of spoon task failure.
More details at https://docs.gradle.org/current/userguide/tutorial_gradle_command_line.html#sec:continue_build_on_failure

**Comment by roman-mazur** [comment]
Feel free to reopen if adding a listener still makes sense to you.

**Comment by Pavel87** [comment]
Hi Roman,
Thanks this seems to work. I was trying to use --continue initially but somehow it wasn't giving me the right results at the beginning but now it seems to do the job perfectly.
Thanks for pointing it out!
