### ISSUE TITLE
Slow test execution on emulator

### ISSUE THREAD

**Issue by ronocod** [stanfy/spoon-gradle-plugin#131]
We're seeing tests running 3-4x slower when we use this plugin with Gradle 3.1. In normal runs the time between `STRL.testStarted` and `STRL.testEnded` log messages is 2-4s, on Gradle 3.1 tests are taking up to 20s each.

* Running under Gradle 2.14.1 or 3.0 seems to fix the problem.
* Around 1 in 20 tests will run at 1-1.5x normal speed, the rest are consistently 3-4x.
* We're using Android Build Tools 2.2.0, running on an API 24 emulator. All SDK tools are up-to-date.
* We're running with the config:
```groovy
spoon {
    noAnimations = true
    codeCoverage = true
    grantAllPermissions = true
}
```

**Comment by ronocod** [comment]
Seeing this consistently now with Gradle 3.0 since I updated our local Android SDK installation today. The issue may not be related to this plugin.

**Comment by ronocod** [comment]
Can reproduce this with Gradle 2.14.1 now, I think this must be an issue with newer emulator versions

**Comment by ronocod** [comment]
The problem is happening intermittently now, it seems like this is an emulator issue.

**Comment by roman-mazur** [comment]
So is it an emulator issue? :)

**Comment by ronocod** [comment]
It looks like it, after restarting the emulator today the problem hasn't happened since, although previous restarts didn't fix it. Either way we've been using the same version of this plugin throughout this so I don't think it's caused by this.
