### ISSUE TITLE
Cut a new version please

### ISSUE THREAD

**Issue by LesterTheTester** [stanfy/spoon-gradle-plugin#132]
I'd love to use the latest build since it contains my changes that got rolled into spoon-runner-1.7.0  #129 .  When are you planning on cutting a new release for maven?

**Comment by roman-mazur** [comment]
I do not see much sense to release this plugin version every time the spoon project is updated unless the plugin must adapt. You can always specify what version of spoon-runner you want to use declaring it in the dependencies:
```
dependencies {
  classpath 'com.stanfy.spoon:spoon-gradle-plugin:1.2.2'
  classpath 'com.squareup.spoon:spoon-runner:1.7.0'
}
```
This will override transient dependency declaration defined by the plugin.

Speaking about the new release, I think it makes sense to investigate #131 first.
