### ISSUE TITLE
Disable animated gifs from build.gradle

### ISSUE THREAD

**Issue by tir38** [stanfy/spoon-gradle-plugin#133]
There is already a way to disable animated gifs if I run Spoon from CL (https://github.com/square/spoon#execution) It would be nice if this was a flag that could be added in build.gradle.

**Comment by ligi** [comment]
Would really be nice - especially as they seem to consume time but I do not even see them in the resulting report

**Comment by roman-mazur** [comment]
Here you can find a list of available options from gradle plugin:
https://github.com/stanfy/spoon-gradle-plugin/blob/master/src/main/groovy/com/stanfy/spoon/gradle/SpoonExtension.groovy

You can configure it with 
```
spoon {
  noAnimations = true
}
```

**Comment by tir38** [comment]
You should definitely have all of that info in the readme. Or at very least link to it.
