### ISSUE TITLE
How to get standard XML junit output with spoon

### ISSUE THREAD

**Issue by tandroidt** [stanfy/spoon-gradle-plugin#141]
Hi!
How can I get a standard XML junit output when using spoon?
I saw in Issue  #100 ( https://github.com/square/spoon/issues/100) that you added this option, but couldn't find out how to use it.
I want to use the xml output in JIRA.

Thanks!

**Comment by artem-zinnatullin** [comment]
Yes, it's in `build/spoon/buildTypeFlavor/junit-reports`.

**Comment by tandroidt** [comment]
Thanks! 
I run it on a real device, with jenkins.
So I looked for this path on the jenkins slave computer and I only have under build the "spoon-output" folder where we put the index.html file.

Do I need to use any special flag to make spoon crate the xml?  
right now I run it with these command :

   java -jar $SPOON_JAR --apk $APK_PATH --test-apk $TEST_APK_PATH --output $SPOON_REPORT_PATH --title "$TITLE" --class-name $TEST_SUITE_CLASS

Do I need to add anything?

Thanks!

**Comment by artem-zinnatullin** [comment]
Looks like you're not using Gradle Plugin in which repo you've created
issue, you're launching Spoon jar manually so you need to check Spoon repo
issues instead.

**Comment by tandroidt** [comment]
You are right, thank a lot!
