### ISSUE TITLE
Run a specifix test suite

### ISSUE THREAD

**Issue by tandroidt** [stanfy/spoon-gradle-plugin#146]
Hi!
I didn't understand how to run a specifix variant. where are the tasks generated to? should I run them directly?
Also,
I want to run a specifix test suite I have in Espresso.
How can I do that ? The "className" is suitable for testSuites or only for testClasses?

Thanks!

**Comment by A-Hamdy** [comment]
Hi @tandroidt  Did you manage to find a solution to run specific test variant using Spoon ?

**Comment by tandroidt** [comment]
Yes @A-Hamdy . I just used the flags --class-name  and --method-name . finally my problem was not related to this, the flags works fine.
