### ISSUE TITLE
Need to get the Android device id 

### ISSUE THREAD

**Issue by mgmanikandan87** [stanfy/spoon-gradle-plugin#148]
I need to get the android device id for changing the data set per device level.

**Comment by artem-zinnatullin** [comment]
`adb devices`

**Comment by roman-mazur** [comment]
If you connect devices to your machine, `adb devices` will give you a list of their serial numbers. These serial numbers can be used in spoon plugin configuration to include or exclude specific devices.

**Comment by mgmanikandan87** [comment]
@roman-mazur and @artem-zinnatullin 
Thanks for quick response,  I have explained little brief. 

Running the adb devices command and getting the devices id is fine, 
In my case I need to pass phone number as a param while running the cases on two devices parallelly same phone number is passing both devices instead i need to maintain the two different data set which spoon should pick it accordingly device id.

In this scenario, either spoon have to give feature like per device per data set  or spoon should be expose the api called current android serial id Spoon.getCurrentSerialID();, so that i can change the data set accordingly.
