### ISSUE TITLE
[AGP 3.0] - Build failure reason org.gradle.execution.TaskSelectionException: Task 'spoonDebug' not found in root project ''. Some candidates are: 'stopDebug'.

### ISSUE THREAD

**Issue by jaredsburrows** [stanfy/spoon-gradle-plugin#162]
## Details:
Trying to update from Android Gradle Plugin `2.3.3` to `3.0.0`.

### With `2.3.3`:
```
spoon - Runs all the instrumentation test variations on all the connected devices
spoonDebugAndroidTest - Runs instrumentation tests on all the connected devices for 'debugAndroidTest' variation and g
```

### With `3.0.0`:
```
spoon - Runs all the instrumentation test variations on all the connected devices
```

## Error:
```
Build failure reason org.gradle.execution.TaskSelectionException: Task 'spoonDebug' not found in root project 'android'. Some candidates are: 'stopDebug'. 
```

**Comment by autonomousapps** [comment]
Duplicate of https://github.com/stanfy/spoon-gradle-plugin/issues/155

**Comment by jaredsburrows** [comment]
@autonomousapps Thanks. That issue should be renamed as it is not Gradle's fault, it is the Android Grade Plugin fault.

**Comment by autonomousapps** [comment]
I'll leave that to a maintainer to figure out :)

Btw, if you look at the PR associated with that other ticket, you'll find a solution using a snapshot build that will get you rolling again.

**Comment by jaredsburrows** [comment]
@autonomousapps I hope that the make a release soon!
