### ISSUE TITLE
Is there any plan to migrate to Android Gradle Plugin 3.0

### ISSUE THREAD

**Issue by jimxj** [stanfy/spoon-gradle-plugin#163]
Hi,

I just migrated my Android project to Android Gradle Plugin 3.0 and found out the command `spoonDebugAndroidTest` is no longer working. I am wondering is there any plan to migrate to Android Gradle Plugin 3.0 ?

Thanks
Jim

**Comment by dweebo** [comment]
See https://github.com/stanfy/spoon-gradle-plugin/pull/161
