### ISSUE TITLE
Version 0.14.1 does not work with latest Android Gradle Plugin

### ISSUE THREAD

**Issue by asfalcone** [stanfy/spoon-gradle-plugin#37]
Android Gradle Plugin 1.1.0-rc1 was released yesterday and it appears that the latest version of the spoon-gradle-plugin does not work with it.

Error:
java.lang.NullPointerException: Cannot get property 'outputs' on null object
	at com.stanfy.spoon.gradle.SpoonPlugin.createTask(SpoonPlugin.groovy:97)

https://github.com/stanfy/spoon-gradle-plugin/blob/master/src/main/groovy/com/stanfy/spoon/gradle/SpoonPlugin.groovy#L97

It seems like testedVariant is null. I don't see anything in the latest version of the Android Gradle Plugin that indicates that this was deprecated though.

**Comment by ligi** [comment]
I second that - especially sad as 1.1 brings this awesome unit-testing support ..

**Comment by ligi** [comment]
also happening with  1.1.0-rc2

**Comment by roman-mazur** [comment]
We should wait for 1.1.0. It will either be resolved on Android plugin side
or we'll make an update here.

**Comment by roman-mazur** [comment]
The problem seems to be resolved.
https://code.google.com/p/android/issues/detail?id=140267
If the latest version of this plugin does not work with 1.1.0, we'll fix it.

**Comment by ligi** [comment]
1.1.0 is now released and spoon works again - so this can be closed
