### ISSUE TITLE
Android JUnit 4 Tests Fail with this Plugin

### ISSUE THREAD

**Issue by swengconsultant** [stanfy/spoon-gradle-plugin#38]
Hi,

I have a number of tests for Android using JUnit 4 (https://code.google.com/p/android-test-kit/wiki/AndroidJUnitRunnerUserGuide).When I run 'gradle spoon'  it fails with the following error:

>Execution failed for task ':app:spoonDebugTest'.
> Method name 'atTestAnnotated' does not start with 'test'.

Is there a plan to fix this for JUnit 4 style tests?

Regards

**Comment by roman-mazur** [comment]
It seems to be a Spoon issue. See https://github.com/square/spoon/issues/220
