### ISSUE TITLE
Could not resolve spoon dependencies

### ISSUE THREAD

**Issue by jthalliley** [stanfy/spoon-gradle-plugin#41]
I can't seem to get spoon to run on my project.  Is there a version mismatch?

Thanks,
Tom

build.gradle:
----------------------------------------------------------------------------
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.0.0'
        classpath 'org.robolectric:robolectric-gradle-plugin:0.14.+'
        classpath 'com.jakewharton.hugo:hugo-plugin:1.1.0'
        classpath 'com.stanfy.spoon:spoon-gradle-plugin:0.14.1' 
    }
}

allprojects {
    repositories {
        mavenCentral()
    }
}

app/build.gradle:
----------------------------------------------------------------------------
apply plugin: 'com.android.application'
apply plugin: 'robolectric'
apply plugin: 'hugo'
apply plugin: 'spoon'

dependencies {

    ...
    compile "com.squareup.spoon:spoon-client:1.1.2"
    ...
    androidTestCompile ('com.android.support.test.espresso:espresso-core:2.0') {
        exclude group: 'com.android.support.test'
        exclude group: 'javax.inject'
    }

}

spoon {
    debug = true;

    if (project.hasProperty('spoonClassName')) {
        className = project.spoonClassName
    }
}

**Comment by jthalliley** [comment]
I changed to 
   androidTestCompile "com.squareup.spoon:spoon-client:1.1.2"

but that had no effect.

**Comment by roman-mazur** [comment]
It's a known issue #1. Please see https://github.com/stanfy/spoon-gradle-plugin/issues/1#issuecomment-28903983 for a workaround.
