### ISSUE TITLE
"Could not find test class" error when I take a screenshot

### ISSUE THREAD

**Issue by ehro** [stanfy/spoon-gradle-plugin#51]
Hi,

When I try to take a screenshot, I get this message:

java.lang.IllegalArgumentException: Could not find test class!
    at com.squareup.spoon.Spoon.findTestClassTraceElement(Spoon.java:171)
    at com.squareup.spoon.Spoon.screenshot(Spoon.java:50)

My test cases use Robotium + Gradle + Spoon Plugin (com.stanfy.spoon:spoon-gradle-plugin:1.0.1) .

Can you help me? If I remove the line, the tests are executed properly.

**Comment by roman-mazur** [comment]
I can depend on how you invoke `screenshot` method (what place from).
You should provide a test example.

**Comment by roman-mazur** [comment]
Please reopen with an example.

**Comment by rafaelaazevedo** [comment]
I am having the same problem, but I am using Cucumber as well, not sure if it's because my runner is CucumberInstrumentation. 

I am taking screenshot inside a given step:

@Given("^I open the login screen$")
    public void test() {
        mSolo = new Solo(getInstrumentation(), getActivity());
        Spoon.screenshot(mSolo.getCurrentActivity(), "Test");
}

My Runner:

public class Instrumentation extends CucumberInstrumentation {
    @Override
    public void onStart() {
        runOnMainSync(new Runnable() {
            @Override
            public void run() {
                final Application app = (Application) getTargetContext().getApplicationContext();
                final String simpleName = Instrumentation.class.getSimpleName();

                // Unlock the device so that the tests can input keystrokes.
                ((KeyguardManager) app.getSystemService(Context.KEYGUARD_SERVICE))
                    .newKeyguardLock(simpleName)
                    .disableKeyguard();

                // Wake up the screen.
                ((PowerManager) app.getSystemService(Context.POWER_SERVICE))
                    .newWakeLock(PowerManager.FULL_WAKE_LOCK | PowerManager
                        .ACQUIRE_CAUSES_WAKEUP | PowerManager.ON_AFTER_RELEASE, simpleName)
                    .acquire();
            }
        });

        super.onStart();
    }
}

**Comment by roman-mazur** [comment]
See my comment in different thread https://github.com/stanfy/spoon-gradle-plugin/issues/75#issuecomment-143258735
