### ISSUE TITLE
Device logs not attached to tests (Please update Spoon lib)

### ISSUE THREAD

**Issue by tmelz** [stanfy/spoon-gradle-plugin#53]
This was fixed with https://github.com/square/spoon/commit/9705bc8b73343486446389cd2a04d65bfe77d299, would you mind bumping to spoon runner 1.1.9 and pushing a release?

**Comment by roman-mazur** [comment]
1.0.2 will definitely do it, but there some other issues that should be solved before the next release...
Meanwhile you can simply add 
```groovy
classpath 'com.squareup.spoon:spoon-runner:1.1.9'
```
near spoon gradle plugin dependency and gradle will use the newer version.

**Comment by roman-mazur** [comment]
Actually there is no 1.1.9 version yet :) But you might use a snapshot.

**Comment by tmelz** [comment]
Looks like it's up now. A release here would be much appreciated :)

**Comment by roman-mazur** [comment]
Released 1.0.2. Should be soon in Maven Central.

**Comment by rafaelaazevedo** [comment]
Sorry, to come this closed issue, but I am having problem with the logs too, it is not showing any information. Am I missing something ? Thank you !
