### ISSUE TITLE
Could not find class: apple.awt.CGraphicsEnvironment

### ISSUE THREAD

**Issue by fantasy1022** [stanfy/spoon-gradle-plugin#54]
When I execute multi screenshots in a test method, Spoon would generate a gif for those screenshots.
I meet an error "Could not find class: apple.awt.CGraphicsEnvironment" in OS X environment. Does it has workaround about this condition?

**Comment by roman-mazur** [comment]
What version of the plugin are you using?

**Comment by fantasy1022** [comment]
I use plugin version in "com.stanfy.spoon:spoon-gradle-plugin:1.0.1".

**Comment by roman-mazur** [comment]
And does example in this repo work for you?
https://github.com/stanfy/spoon-gradle-plugin/tree/master/example
One of the tests ("Set Text") in this example generates multiple screenshots and I can see a generated gif in the report (on Mac).
You might want to change plugin used plugin version at
https://github.com/stanfy/spoon-gradle-plugin/blob/master/example/build.gradle#L9
(to 1.0.1).

**Comment by roman-mazur** [comment]
It runs multiple flavors, you can see a report opening 
example/app/build/custom-report-dir/free/debug/index.html

**Comment by fantasy1022** [comment]
I can not find 1.0.2-SNAPSHOT version in mavenLocal. Do I need another setting to set path of mavenLocal?

**Comment by fantasy1022** [comment]
I use example and set 1.0.1 and still meet the same problem. But it is no problem to use Mac of my colleague to run test. Does the configure of computer environment influence the result about generating gif? However, I have no idea about this. Do you have any idea about this? Thanks.

**Comment by roman-mazur** [comment]
You probably have some problems with Java setup (paths, missing jars in jdk libs folder, anything).

**Comment by fantasy1022** [comment]
Ok, I see. I would try setup Java again. Thanks for your help!

**Comment by sregg** [comment]
@fantasy1022 were you able to fix that issue?

**Comment by fantasy1022** [comment]
I do not find solution to fix this issue.

**Comment by germanb** [comment]
I'm having the same problem when I run spoon from android studio. I think that maybe is related with this issue
https://code.google.com/p/android/issues/detail?id=162448.

When running from the terminal works fine for me.
