### ISSUE TITLE
How to uninstall the existing app in all devices at the same time while running spoon

### ISSUE THREAD

**Issue by sayoojvalsan-demandmedia** [stanfy/spoon-gradle-plugin#56]
I am looking for a way to remove existing app in all devices before running spoon. Is there any config in spoon which does that ?

I usually use gradle spoon<Flavour name>  to test .
gradle uninstallAll doesnt run in parallel.

**Comment by roman-mazur** [comment]
AFAIK Spoon does not provide such an option. And there is no such option in this plugin as well.
