### ISSUE TITLE
Plugin in Jenkins ?

### ISSUE THREAD

**Issue by Bukoow** [stanfy/spoon-gradle-plugin#57]
Hi !

I work in Android with Continuous Integration using Jenkins, in order to automate tests, build etc...

I'm very interested with Spoon and I've found your plugin.

But is it possible to use it in this type of control (Jenkins etc...) ? By script ?

I've just start in CI so can you explain me ?

Thank you very much !

**Comment by roman-mazur** [comment]
There is no plugin for spoon.
You might use a plugin for Android emulator 
https://wiki.jenkins-ci.org/display/JENKINS/Android+Emulator+Plugin
to run an emulator during the build.
Then configure your build steps to execute `spoon` tasks.
And collect JUnit test results and HTML reports using post-build actions (see your job configuration).
