### ISSUE TITLE
Support for TeamCity

### ISSUE THREAD

**Issue by RomainPiel** [stanfy/spoon-gradle-plugin#58]
Hey!
It would be awesome to have support for TeamCity with this plugin. I managed to integrate it nicely and look at the reports and all but I'd love have a quick and clean summary of the tests. https://github.com/x2on/gradle-spoon-plugin is using https://github.com/x2on/teamcity-status-message-helper for that. Do you think we could have the same feature with this plugin?
Thanks for your work by the way!

**Comment by roman-mazur** [comment]
We do not use TeamCity internally, hence, there is a little somebody here will work on it.
But does not TeamCity support JUnit xml reports?

**Comment by RomainPiel** [comment]
Yes I think it supports xml reports. The problem is that you will get multiple xml reports when running the tests on multiple devices. Not sure how it would ideally look but something like "tests failed on 3 devices out of 5" or adding percentages of failing tests would look pretty neat.

**Comment by roman-mazur** [comment]
I definitely have no bandwidth for this. And not sure anybody here really wants to support this.
