### ISSUE TITLE
Allow passing arbitrary -e args to SpoonRunner

### ISSUE THREAD

**Issue by ncalexan** [stanfy/spoon-gradle-plugin#60]
This is the companion to the code that landed in https://github.com/square/spoon/pull/266.

I want this to be able to pass "-e package=my.package".

**Comment by roman-mazur** [comment]
:+1: Feel free to submit a PR!

Here's where you can pass the parameters to spoon: https://github.com/stanfy/spoon-gradle-plugin/blob/v1.0.2/src/main/groovy/com/stanfy/spoon/gradle/SpoonRunTask.groovy#L105-L116
