### ISSUE TITLE
Error [INSTALL_PARSE_FAILED_INCONSISTENT_CERTIFICATES]

### ISSUE THREAD

**Issue by brandoFS** [stanfy/spoon-gradle-plugin#69]
I'm getting this error and no tests are being run.
:app:spoonDebugAndroidTest
2015-07-23 16:41:50 [SR.runTests] Executing instrumentation suite on 1 device(s).
2015-07-23 16:42:09 [SDR.run] [009ee8a01646b2b6] test apk install failed.  Error [INSTALL_PARSE_FAILED_INCONSISTENT_CERTIFICATES]
:app:spoonDebugAndroidTest FAILED

I tried both ./gradlew spoon and ./gradlew spoonDebugAndroidTest 

I've uninstalled the Application beforehand so the device is starting out clean 

tried with a moto g and nexus 4 device

**Comment by roman-mazur** [comment]
Probably you removed only application apk. Tests are bundled into a separate apk and are separately installed.
Try running `./gradlew uninstallAll` to remove all the possible variants from your device or `./gradlew uninstallDebugAndroidTest` to delete the test apk.

**Comment by brandoFS** [comment]
looks like that worked! thanks!
