### ISSUE TITLE
With Gradle 2.5 and plugin 1.3.0. if you change apk name fail

### ISSUE THREAD

**Issue by danielgomezrico** [stanfy/spoon-gradle-plugin#70]
This just start happening with new `Gradle 2.5` and `Gradle Plugin 1.3.0`

I have gradle changing my apk name like this:

```
testBuildType "mock"

android {
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def apk = output.outputFile
            def newName = "customer-${apk.name}-v${appVersionName}-b${appVersionCode}.apk"

            output.outputFile = new File(apk.parent, newName)
        }
    }
}
```

And when I run my tests `./gradlew clean spoonMockAndroidTest` it fails with:

```
:app:spoonMockAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':app:spoonMockAndroidTest'.
> File '.../app/build/outputs/apk/app-mock-androidTest-unaligned.apk' specified for property 'instrumentationApk' does not exist.
> File '...app/build/outputs/apk/app-mock.apk' specified for property 'applicationApk' does not exist.
```

**Comment by roman-mazur** [comment]
I think your closure that changes the name is used after spoon creates the tasks.
You might try placing `apply plugin: 'spoon'` after your code or wrapping your code with `afterEvaluate`:
```groovy
afterEvaluate {
  android {
      applicationVariants.all { variant ->
          variant.outputs.each { output ->
              def apk = output.outputFile
              def newName = "customer-${apk.name}-v${appVersionName}-b${appVersionCode}.apk"

              output.outputFile = new File(apk.parent, newName)
          }
      }
  }
}
```

**Comment by sregg** [comment]
I tried both solutions and none of them work.
@danielgomezrico have you found a fix for this?

**Comment by sregg** [comment]
I finally found a way to fix it by doing the opposite, wrapping the plugin application in `afterEvalute`

```
afterEvaluate {
        // need to apply Spoon plugin after evaluate so it can get the right apk name
        // see https://github.com/stanfy/spoon-gradle-plugin/issues/70
        apply plugin: 'spoon'
        spoon {
            debug = true;
        }
    }
```

**Comment by danielgomezrico** [comment]
That give´s me `Instrumentation run failed due to 'java.lang.NoClassDefFoundError'`. :(

**Comment by hotchemi** [comment]
Anything update?

**Comment by roman-mazur** [comment]
I cannot advice anything better than workarounds here. And it's more gradle or android plugin issue. That said there is a ticket in android bug tracker https://code.google.com/p/android/issues/detail?id=76565 to provide better means for apk name configuration.
Hence, I'm going to close this.

**Comment by pohh** [comment]
@hotchemi  @danielgomezrico  I applied @sregg solution as well as the hint from a stackoverflow post:
http://stackoverflow.com/questions/23693309/renaming-apk-in-gradle

```output.applicationPackage.outputFile``` also needs to be set for spoon gradle build to find  ```applicationApk```.

```
	buildTypes {
		release {
			minifyEnabled true
			applicationVariants.all {variant ->
				variant.outputs.each {output ->
					def alignedOutputFile = output.outputFile
					def unalignedOutputFile = output.packageApplication.outputFile
					// Customise APK filenames (to include build version)
					if (variant.buildType.zipAlignEnabled) {
						// normal APK
						output.outputFile = new File(alignedOutputFile.parent, alignedOutputFile.name.replace(".apk", "-" + customVersionCode + "-" + customVersionName + ".apk"))
					}
					// 'unaligned' APK
					output.packageApplication.outputFile = new File(unalignedOutputFile.parent, unalignedOutputFile.name.replace(".apk", "-" + customVersionCode + "-" + customVersionName + ".apk"))

				}
			}
		}

		debug {
			afterEvaluate {
				apply plugin: 'spoon'
			}
		}
	}
```

Without this I would get:

```File '/path/to/app/src/build/outputs/apk/app-debug.apk' specified for property 'applicationApk' does not exist.````

**Comment by danielgomezrico** [comment]
@pohh  why did you put `applicationVariants.all {variant ->` inside `release`?

**Comment by sayoojvalsan-demandmedia** [comment]
Hi All,

I am still facing this issue. I tried all above, cudn get it working.

My config

buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
        mavenCentral()

    }


    dependencies {
        classpath 'com.stanfy.spoon:spoon-gradle-plugin:1.0.2'
    }
}


apply plugin: 'com.android.application'
apply plugin: 'spoon'



android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 23

        multiDexEnabled = true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"


    }


 
    signingConfigs {


    buildTypes {
        release {
            minifyEnabled false
            proguardFiles  'proguard-rules.pro'

            signingConfig signingConfigs.release
            applicationVariants.all { variant ->
                variant.outputs.each { output ->
                    output.outputFile = new File(output.outputFile.parent, output.outputFile.name.replace(".apk", "-" + defaultConfig.versionName + ".apk"))
                }
            }

        }
        debug {
            versionNameSuffix "-DEBUG"
            minifyEnabled false
            proguardFiles  'proguard-rules.pro'

        }
    }


    dexOptions {
        jumboMode true
        javaMaxHeapSize "4g"
        incremental true
    }
}


dependencies {

androidTestCompile 'com.squareup.spoon:spoon-client:1.1.9'

}

**Comment by Stefantost** [comment]
I also had this error before:

> 
> File '.../app/build/outputs/apk/app-mock-androidTest-unaligned.apk' specified for property 'instrumentationApk' does not exist.


But this: 
```
defaultConfig {
    applicationId packageName
    ...
    setProperty("archivesBaseName", "app-${versionName}")
}
```

works much better for me than the `applicationVariants.all { variant -> ...` - thing...

**Comment by PhilipAtanassov** [comment]
Another way to make it work is to iterate over the `android.testVariants` in addition to iterating over the `android.applicationVariants` and afterwards apply the spoon plugin like this:
```groovy
android.applicationVariants.all { ApplicationVariant variant ->
    variant.outputs.each { BaseVariantOutput output -> renameOutputApk(variant, output) }
}
android.testVariants.all { TestVariant variant ->
    variant.testedVariant.outputs.each { BaseVariantOutput output -> renameOutputApk(variant, output) }
}
apply plugin: 'spoon' // apply the plugin after iterating over the app and test variants above
```
where, `renameOutputApk` is something along the lines of:
```groovy
def renameOutputApk(ApkVariant variant, BaseVariantOutput output) {
    output.outputFile = new File(output.outputFile.parent,
            "app-v${project.ext.version}.apk")
}
```
