### ISSUE TITLE
Logs are empty when using Spoon gradle with Robotium

### ISSUE THREAD

**Issue by rafaelaazevedo** [stanfy/spoon-gradle-plugin#76]
I am using spoon gradle with robotium and cucumber and I can take the screenshots and see on the report, but the logs are completely empty. 

My Build.gradle:

 classpath('com.stanfy.spoon:spoon-gradle-plugin:1.0.3') {
  exclude module: 'guava'
  }

 classpath 'com.squareup.spoon:spoon-runner:1.2.0'
My app-build.gradle:

dependencies{
 androidTestCompile 'com.squareup.spoon:spoon-client:1.2.0'
 androidTestCompile 'com.jayway.android.robotium:robotium-solo:5.5.1'
}

spoon {
 debug = true
 if (project.hasProperty('spoonFailNoConnectedDevice')) {
    failIfNoDeviceConnected = true
 }

 if (project.hasProperty('cucumberOptions')) {
    instrumentationArgs = ["cucumberOptions=" + "'${project.cucumberOptions}'"]
 }

}
I am running through commandline, the command is:

gradle spoon -PspoonFailNoConnectedDevice -PcucumberOptions='--tags @smoke'
My instrumentation runner:

public class Instrumentation extends CucumberInstrumentation {
@Override
public void onStart() {
    runOnMainSync(new Runnable() {
        @Override
        public void run() {
            Application app = (Application) getTargetContext().getApplicationContext();
            String simpleName = Instrumentation.class.getSimpleName();

            // Unlock the device so that the tests can input keystrokes.
            ((KeyguardManager) app.getSystemService(KEYGUARD_SERVICE)) //
                .newKeyguardLock(simpleName) //
                .disableKeyguard();
            // Wake up the screen.
            ((PowerManager) app.getSystemService(POWER_SERVICE)) //
                .newWakeLock(FULL_WAKE_LOCK | ACQUIRE_CAUSES_WAKEUP | ON_AFTER_RELEASE, simpleName) //
                .acquire();
        }
    });

    super.onStart();
}

}

Thank you !

**Comment by rafaelaazevedo** [comment]
nobody to comment this issue ?

**Comment by roman-mazur** [comment]
Sorry for a poor feedback. We've recently released a new 1.0.4 version.
You might try it and see if the issue is resolved for you.
But it sounds like something related to https://github.com/square/spoon/issues/302

**Comment by rafaelaazevedo** [comment]
No problem, I've tested and I am still having the same problem... The logs are empty :(

**Comment by rafaelaazevedo** [comment]
I think the problem in os Spoon side not the plugin, so I am going to close this issue
