### ISSUE TITLE
No extension allowing to set applicationApk and instrumentationApk

### ISSUE THREAD

**Issue by FisherHUB** [stanfy/spoon-gradle-plugin#78]
Maybe I am too inexperienced with groovy yet but what I find problematic is that my project has a lot of various flavours generating different builds. I am having trouble to access @InputFile applicationApk and instrumentationApk. My spoon wants to use app-debug.apk and app-AndroidTest-unaligned.apk to my tests no mather what I do. It would be nice if file with extensions:

https://github.com/stanfy/spoon-gradle-plugin/blob/master/src/main/groovy/com/stanfy/spoon/gradle/SpoonExtension.groovy

contained some fields that allows you to set paths to those files.

**Comment by roman-mazur** [comment]
The plugin selects an apk provided by the Android gradle plugin. Basically it tests the same apk which is tested by `connectedCheck` task.
You can get more information how testing is configured with Android plugin here:
http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Testing

Spoon creates tasks for all the project flavours. But only one build type is tested (debug by default). You can change the testing build type with
```groovy
android {
    ...
    testBuildType "release"
}
```
