### ISSUE TITLE
How to generate coverage report with spoon plugin?

### ISSUE THREAD

**Issue by mbmc** [stanfy/spoon-gradle-plugin#79]
Coverage report can be generated by adding:
```
buildTypes {
    debug {
        testCoverageEnabled true
    }
}
```
and running `gradlew connectedCheck`

But how to enable it while running `gradlew spoon`?

**Comment by roman-mazur** [comment]
It's currently not supported. Basically connectedCheck has dependencies on coverage report tasks. Spoon tasks do not. In fact this plugin was created when there were no test coverage support in Android plugin and nobody has done anything to integrate it.
You can do it in your project though. Something like `tasks.spoon.dependsOn '{coverageReportTaskName}'`

**Comment by JonasJurczok** [comment]
This feature would be really cool :)
I just switched to spoon to run my tests on multiple emulators (as travis failed here repeatedly) and the only thing that I could not transport so far are coverage reports.

Will read into the gradle dependency workaround. But +1 for the issue anyway :)

**Comment by JonasJurczok** [comment]
I tried adding the dependency from spoon to 'createDebugCoverageReport' (which according to my understanding is the default task for coverage reports for the debug build). Unfortunately this results in the tests running twice.. once for creating the coveragereport (as it runs connectedCheck as a dependency) and once for spoon.

Is this a misunderstanding on my part or something that actually has to be built into the spoon plugin to work properly (I'm new to gradle so.. no idea :) )?

**Comment by roman-mazur** [comment]
It looks like plugin modification is required because Jacoco (used by Android plugin) uses on-the-fly instrumentation of code during tests run.

**Comment by bagintz** [comment]
This would be very helpful

**Comment by ObjectiveTruth** [comment]
:+1:

**Comment by phq** [comment]
really need this feature

**Comment by manishgo** [comment]
Please have a look at this https://github.com/square/spoon/pull/332/files/7ddb21e99b2d33ee98c0772d2dd655c4fa131b97#r60989014

**Comment by jaredsburrows** [comment]
Do we still need 

```
buildTypes {
    debug {
        testCoverageEnabled true
    }
}
```
for spoon to work

```
spoon {
    codeCoverage = true
}
```
?

**Comment by jainsahab** [comment]
@jaredsburrows **Yes**, we do need to add the following configuration to generate the coverage.
```
buildTypes {
    debug {
        testCoverageEnabled true
    }
}
```

With this configuration, the build (APK) is generated would be emma instrumented build which is required by on-the-fly instrumentation.

You can also have a look at [this issue](https://github.com/square/spoon/issues/403).

**Comment by rahul-narkhede** [comment]
@jainsahab 
When I do 
```
buildTypes {
    debug {
        testCoverageEnabled true
    }
}
```

My androidTests with espresso fail saying "No Tests found"  .  When I remove the above flag,  the spoon can identify and run all the test.  I was trying to enable jacoco coverage for my androidTest
