### ISSUE TITLE
The test code contains Unicode characters, and the resulting report has an error.

### ISSUE THREAD

**Issue by ouguangqian** [stanfy/spoon-gradle-plugin#83]
hello,When I write test code, the test code contains Unicode characters, resulting in a report error

app debugAndroidTest
4 tests run across 2 devices with 4 passing and 0 failing in 45 seconds at 2015-11-21 08:59 ����

**Comment by roman-mazur** [comment]
Could you provide an example?

**Comment by ouguangqian** [comment]
I set the browser's Encoding to GB2312, it's OK !thank you!
