### ISSUE TITLE
How can i use spoon-gradle-plugin to test only apk!

### ISSUE THREAD

**Issue by ouguangqian** [stanfy/spoon-gradle-plugin#84]
hello,I have an apk,but no codes,I want to test the apk with spoon,how do this? thank you/1

**Comment by roman-mazur** [comment]
Spoon is supposed to be used for running Android instrumentation tests. It usually means you need the main application code to make tests that can access Activities under the test.

For your use case, you probably should take a look at [UiAutomator](http://developer.android.com/tools/testing-support-library/index.html#UIAutomator). It's designed to be used in such cases.

**Comment by roman-mazur** [comment]
That said, this kind of questions should be asked on stackoverlfow.
