### ISSUE TITLE
Android gradle plugin 1.5.0  not compatiable

### ISSUE THREAD

**Issue by nick252** [stanfy/spoon-gradle-plugin#85]
Please, provide update

**Comment by ibamadd** [comment]
looks like it's been updated to 2.0.0-alpha2

**Comment by shareme** [comment]
yes and we are at spoon runner 1.3.1

**Comment by roman-mazur** [comment]
Should work with version 1.0.4 (will be in Maven Central in few hours). Please reopen if it does not work for you.
