### ISSUE TITLE
Execution failed for task ':app:spoonDebugAndroidTest'. > com.android.ddmlib.IDevice.installPackage(Ljava/lang/String;Z[Ljava/lang/String;)Ljava/lang/String;

### ISSUE THREAD

**Issue by ouguangqian** [stanfy/spoon-gradle-plugin#88]
I Update Gradle plugin to v.1.5.0 and Update to ddmlib 24.5.0,bug i also have the problem

What went wrong: Execution failed for task ':app:spoonDebugAndroidTest'. > com.android.ddmlib.IDevice.installPackage(Ljava/lang/String;Z[Ljava/lang/String;)Ljava/lang/String;
the follows is my gradle file:
apply plugin: 'com.android.application'

buildscript {
repositories {
jcenter()
}
dependencies {
// 该版能生成报告
classpath 'com.android.tools.ddms:ddmlib:24.5.0'
classpath 'com.android.tools.build:gradle:1.5.0'
classpath 'com.stanfy.spoon:spoon-gradle-plugin:1.0.2'
}
}

apply plugin: 'spoon'

android {
compileSdkVersion 23
buildToolsVersion "23.0.2"

defaultConfig {
    applicationId "com.pateo.autotest"
    testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    minSdkVersion 18
    targetSdkVersion 23
    versionCode 1
    versionName "1.0"
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
}

dependencies {
compile fileTree(dir: 'libs', include: ['*.jar'])
testCompile 'junit:junit:4.12'
compile 'com.android.support:appcompat-v7:23.0.1'
compile 'com.android.support:design:23.0.1'

// Instrumentation tests
// androidTestCompile 'com.android.support.test.espresso:espresso-contrib:2.1'

androidTestCompile 'com.android.support.test:runner:0.4'
// Set this dependency to use JUnit 4 rules
androidTestCompile 'com.android.support.test:rules:0.4'

androidTestCompile 'com.android.support.test.uiautomator:uiautomator-v18:2.1.2'
// spoon 测试框架
androidTestCompile 'com.squareup.spoon:spoon-client:1.2.1'
}

And 
@edenman commented 6 hours ago
@ouguangqian it looks like spoon-gradle-plugin hasn't been updated to point at spoon-runner 1.2.1. You can either submit a PR to that project to upgrade, or just live with it being broken in 24.5.0 for now.

Thanks !

**Comment by FisherHUB** [comment]
Hello. Try update libs in your code (in general, for example there is 2.2.1 espresso already):

Change:
classpath 'com.stanfy.spoon:spoon-gradle-plugin:1.0.2'

to:
classpath 'com.stanfy.spoon:spoon-gradle-plugin:1.0.4-SNAPSHOT'

Also, you add spoon-runner, because I see you are not using it:

classpath 'com.squareup.spoon:spoon-runner:1.2.1'

**Comment by sayoojvalsan-demandmedia** [comment]
I am getting    Could not find com.stanfy.spoon:spoon-gradle-plugin:1.0.4-SNAPSHOT.

**Comment by roman-mazur** [comment]
Dup of #85.
Please try 1.0.4 version with the latest Android SDK.
@sayoojvalsan-demandmedia  snapshots can be found in
```groovy
repositories {
  maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}
```
But 1.0.4 should be available in Maven Central in few hours.
