### ISSUE TITLE
Not able to set custom spoon params in afterEvaluate

### ISSUE THREAD

**Issue by sayoojvalsan-demandmedia** [stanfy/spoon-gradle-plugin#93]
Hi All,

My project has multidex enabled and uses gradle 1.5.0. I fixed the apk name change issue, but now I am not able to set custom args to spoon. I feel there is something to do with afterEvaluate snippet I have.

Here is my set up - 
```
buildscript {
     repositories {
         mavenCentral()
     }


    dependencies {
        classpath 'com.stanfy.spoon:spoon-gradle-plugin:1.0.4'
    }
}


apply plugin: 'com.android.application'
apply plugin: 'spoon'



android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 23

        multiDexEnabled = true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
 }


 
   signingConfigs {
     
        release {
        }
    }


    buildTypes {
        release {
            minifyEnabled false
            proguardFiles  'proguard-rules.pro'

            signingConfig signingConfigs.release
            applicationVariants.all { variant ->
                variant.outputs.each { output ->
                    output.outputFile = new File(output.outputFile.parent, output.outputFile.name.replace(".apk", "-" + defaultConfig.versionName + ".apk"))
                }
            }
     afterEvaluate {
                apply plugin: 'spoon'
                spoon {
                    debug = true
                    className = 'com.xxx.xxx.test.AndroidLargeTestSuite'

                    if (project.hasProperty('spoonClassName')) {
                        className = project.spoonClassName
                    }
                }
            }

        }
        debug {
            versionNameSuffix "-DEBUG"
            minifyEnabled false
            proguardFiles  'proguard-rules.pro'

        }
    }


    dexOptions {
        jumboMode true
        javaMaxHeapSize "4g"
        incremental true
    }
}


dependencies {

    androidTestCompile 'com.squareup.spoon:spoon-client:1.3.1'

}
```
Now I get

No such property: debug for class: com.android.build.gradle.internal.dsl.BuildType_Decorated

when adding
          spoon {
                    debug = true
                    className = 'com.xxx.xxx.test.AndroidLargeTestSuite'
                    if (project.hasProperty('spoonClassName')) {
                        className = project.spoonClassName
                    }
                } 

com.xxx.xxx.test.AndroidLargeTestSuite is a test suite.

Note : I tried setting gradle spoon -PspoonClassName=com.xxx.xxx.test.AndroidLargeTestSuite. It just ignore the param and run all the tests in my test package.

**Comment by roman-mazur** [comment]
I believe you should not put `afterEvaluate` inside of `buildTypes` and `buildTypes` inside of `signingConfigs`.

**Comment by sayoojvalsan-demandmedia** [comment]
Just updated the config. My apologies - The buildTypes are not inside of signingConfigs. I will try with afterEvaluate outside the buildTypes. Tks.
