### ISSUE TITLE
Question: is it possible to specify package from which tests should be launched?

### ISSUE THREAD

**Issue by FisherHUB** [stanfy/spoon-gradle-plugin#95]
Hello,

Is it possible to create test launch sets in some way via spoon? 

For example my tests package looks like that:
![My Package](http://i.stack.imgur.com/FY830.png )

And what I would be interested in, is creation of gradle tasks depending on spoon that would allow me to launch tests from each package separately. When I enter [git repository of spoon from square](https://github.com/square/spoon) then under <b>Running Specific Tests</b> paragraph you can find such example:

  ` --e package=com.mypackage.unit_tests `

Is it possible to pass this `package` parameter/property to instrumentationArgs to overwrite directory from which tests are pulled? I will present my try:

My spoon config:
```
spoon {
    debug = true

    baseOutputDir = file("$buildDir/spoon-log")
    if (project.hasProperty('spoonClassName')) {
        className = project.spoonClassName

        if (project.hasProperty('spoonMethodName')) {
            methodName = project.spoonMethodName
        }
    }

    adbTimeout = 60 * 60;
}
```
And based on that I try to create task:
```
task spoonAuthFlowTests(type: GradleBuild, dependsOn: ['spoon']) {
    spoon {
        instrumentationArgs = ["package=com.myapp.instrumentation.flowtests.AuthFlowTests"]
        noAnimations = true;
    }
}
```

But then in my terminal I can see that:
```
2016-01-08 15:13:10 [SDR.run] About to actually run tests for [04ffe19ad317d2e7]
03:13:10 I/RemoteAndroidTest: Running am instrument -w -r   -e package com.myapp.instrumentation.flowtests -e class com.myapp.instrumentation.flowtests.AuthFlowTests.LoginUserFlowTests com.myapp.debug1.test/com.myapp.instrumentation.helper.runner.MyAppTestRunner on lge-nexus_4-04ffe19ad317d2e7
```
So it is still using `com.myapp.instrumentation.flowtests` and didn't narrow test pool to `com.myapp.instrumentation.flowtests.AuthFlowTests`.

Furthermore I can say that I tried to look up in my project `com.myapp.instrumentation.flowtests` string and the only locations where it is used are: tests in package + gradle task presented above. So it isn't hardcoded anywhere. Same location is picked if I start tests by:

`./gradlew spoon`

instead of

`./gradlew spoonAuthFlowTests`

Is the thing I am trying to do possible now? Or does it need additional parameters/method implementation to SpoonRunner class?

**Comment by roman-mazur** [comment]
I answered your question on stackoverflow. It's a better place for such question. I will try to monitor it more actively.
http://stackoverflow.com/questions/34679937/running-instrumentation-tests-from-specific-package-via-spoon-gradle-plugin/34918049#34918049
