### ISSUE TITLE
Question: How to execute differents tests in specifics devices

### ISSUE THREAD

**Issue by marcosd3souza** [stanfy/spoon-gradle-plugin#96]
Hi,

I have two test suite, each of which must be performed on a different device.

it's possible using Spoon ?

Thanks

**Comment by roman-mazur** [comment]
Stackoverflow is a fairly better place for such questions.
There is a similar question there with my answer.
http://stackoverflow.com/questions/34679937/running-instrumentation-tests-from-specific-package-via-spoon-gradle-plugin/34918049#34918049

Also note that you can device IDs and test class/method to run in `spoon` block. You could write your build.gradle file in a ways to get these values from gradle command line. For example,
```groovy
spoon {
  devices = [project.getProperty('spoonDevice')]
  className = project.getProperty('spoonClass')
}
```
Now you can set the device serial no in your command line:
```
./gradlew spoon -PspoonDevice=123456 -PspoonClass=my.Class
```
See [usage section](https://github.com/stanfy/spoon-gradle-plugin#usage) in the readme.
So you could make a script that takes a mapping from device id to a test class, iterates it and calls the task for specific devices and test suites.

Another option you might consider is [test sharding](https://github.com/stanfy/spoon-gradle-plugin#test-sharding). But I'm not sure how to be specific about what test suites must be run on devices.

**Comment by marcosd3souza** [comment]
Hi, thanks for solution. In my project the uses of packages to separate execution tests moments, from device, is best way.
