### ISSUE TITLE
"Timeout getting device list" on 1.0.4 if you don't use the adbTimeout config param

### ISSUE THREAD

**Issue by gdaniels** [stanfy/spoon-gradle-plugin#97]
Reproducible with the plugin example app by removing this line:

https://github.com/stanfy/spoon-gradle-plugin/blob/master/example/app/build.gradle#L57

and then `gradle spoon`.

It looks like the issue stems from the `SpoonRunner.Builder` defaulting the adbTimeout to 0, which eventually gets passed through to `SpoonUtils.initAdb()`.

Can the timeout default be changed to something more reasonable?

**Comment by roman-mazur** [comment]
Yeah, it was introduced in spoon runner 1.2.1 (https://github.com/square/spoon/pull/287).
PR is welcome (I think it should be done in spoon project).

**Comment by gdaniels** [comment]
So you're suggesting to check for 0 values over in SpoonUtils.initAdb() and change them to 30s?  I guess 0 is always (? maybe not always) going to fail, so that's reasonable...  We could also just pass down 30s from the gradle plugin by default.  I'm not sure which is better.

**Comment by roman-mazur** [comment]
I would rather set the default value in the `Builder` to something >0.
This plugin calls `setTimeout` only if timeout is specified by the user.

**Comment by gdaniels** [comment]
Ah, yep.  OK, will submit a PR over there, thanks!

**Comment by gdaniels** [comment]
Merged into latest Spoon, closing this issue.

**Comment by roman-mazur** [comment]
We probably need to bump spoon dep here for the next release.
